# Generated by Django 6.0.5 on 2026-07-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0003_galeria_faq_departamento_asunto_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
