# Generated by Django 6.0.5 on 2026-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_groups_and_payment_methods'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delivery',
            name='unique_active_delivery_factory_store',
        ),
    ]
