# Generated by Django 6.0.5 on 2026-06-04 17:59

from django.db import migrations


def create_statuses(apps, schema_editor):
    Status = apps.get_model("api", "Status")
    statuses_data = [
        Status(
            id=1,
            name="pending",
            description="Represents a entity that is pending and has not yet been processed.",
        ),
        Status(
            id=2,
            name="in_progress",
            description="Represents a entity that is currently being processed or worked on.",
        ),
        Status(
            id=3,
            name="completed",
            description="Represents a entity that has been successfully completed and all necessary actions have been taken.",
        ),
        Status(
            id=4,
            name="cancelled",
            description="Represents a entity that has been cancelled and will not be processed further.",
        ),
        Status(
            id=5,
            name="stopped",
            description="Represents a entity that has been processed but currently stopped.",
        ),
    ]
    Status._base_manager.bulk_create(statuses_data, ignore_conflicts=True)


def remove_statuses(apps, schema_editor):
    Status = apps.get_model("api", "Status")
    Status._base_manager.filter(id__in=[1, 2, 3, 4, 5]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_status_delivery_status"),
    ]

    operations = [migrations.RunPython(create_statuses, reverse_code=remove_statuses)]
