# Generated by Django 6.0.5 on 2026-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_populate_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
