# Generated by Django 6.0.5 on 2026-06-27 17:10

from django.db import migrations
from django.contrib.auth.hashers import make_password


def populate(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    Establishment = apps.get_model("api", "Establishment")
    Factory = apps.get_model("api", "Factory")
    Profile = apps.get_model("api", "Profile")

    default_password = "0987654aA"
    admin_username = "Admin"
    factory_username = "Planta"
    factory_group_name = "Factory manager"
    factory_profile_role_name = "factory"

    if not User._default_manager.filter(username=admin_username).exists():
        User._default_manager.create(
            username=admin_username,
            password=make_password(default_password),
            is_staff=True,
            is_superuser=True,
        )

    factory_user, _ = User._default_manager.get_or_create(
        username=factory_username,
        defaults={
            "password": make_password(default_password),
            "is_staff": False,
            "is_superuser": False,
        },
    )

    try:
        group_factory = Group._default_manager.get(name=factory_group_name)
        factory_user.groups.add(group_factory)
    except Group.DoesNotExist:
        pass

    establishment_obj, _ = Establishment._default_manager.get_or_create(
        name="Planta principal",
        defaults={
            "municipality": "Municipio",
            "neighborhood": "Colonia",
            "street": "Calle",
        },
    )

    Factory._default_manager.get_or_create(establishment=establishment_obj)

    if not Profile._default_manager.filter(user=factory_user).exists():
        Profile._default_manager.create(
            user=factory_user,
            establishment=establishment_obj,
            role=factory_profile_role_name,
        )


def rollback_initial_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Establishment = apps.get_model("api", "Establishment")

    User._default_manager.filter(username__in=["Admin", "Planta"]).delete()
    Establishment._default_manager.filter(name="Planta principal").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_product_img_profile"),
    ]

    operations = [
        migrations.RunPython(populate, rollback_initial_data),
    ]
