# Generated by Django 6.0.5 on 2026-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0010_populate_init_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sku',), name='unique_active_product_sku'),
        ),
    ]
