# Generated by Django 6.0.5 on 2026-07-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0011_alter_product_sku_product_unique_active_product_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selldetail',
            name='unique_active_sell_details_sell_product',
        ),
        migrations.AddConstraint(
            model_name='selldetail',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sell', 'product'), name='unique_active_sell_detail_sell_product'),
        ),
    ]
