# Generated by Django 6.0.5 on 2026-07-20 19:32

import django.db.models.deletion
import django.db.models.manager
import project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0016_sell_received_sell_returned_sell_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('img', models.ImageField(upload_to=project.utils.PathGenerator('products'))),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_mgmt.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
