# Generated by Django 6.0.5 on 2026-08-08 19:59

from django.db import migrations


def seed_bot_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name="Bot")


def unseed_bot_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(name="Bot").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaMedicionIoT", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            seed_bot_group,
            unseed_bot_group,
        ),
    ]