# Generated by Django 6.0.5 on 2026-08-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMedicionIoT', '0002_auto_20260808_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time_seconds',
        ),
    ]
