# Generated by Django 6.0.5 on 2026-07-10 20:00

import project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brand_retailer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=project.utils.PathGenerator('retailers')),
        ),
    ]
