# Generated by Django 6.0.5 on 2026-07-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_galeriaitem_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['order']},
        ),
    ]
